server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaodahao/HelloSpringCloud-config.git #GitHub上面的git仓库名字
          #使用git@github.com:chaodahao/HelloSpringCloud-config.git出现报错，改为上面的
          #另外spring-cloud-config-server的版本也导致报错，最后改为2.2.0.RELEASE即可
          ####搜索目录
          username: chaodahao
          password: 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
          search-paths:
            - HelloSpringCloud-config
      ####读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


